feat: enable S3 retries (#39)
Also enable by default.

Hopefully fixes:

```
could not load link \"baguqeeraidgfgewjrh5ybvjd6yjkoy3zvkghdx6ewcjokuoimded5yxk6hlq\": failed to fetch block for cid baguqeeraidgfgewjrh5ybvjd6yjkoy3zvkghdx6ewcjokuoimded5yxk6hlq:
  RequestError: send request failed
    caused by: Put \"https://prod-ipni-tmp-datastore.s3.us-west-2.amazonaws.com/baguqeeraidgfgewjrh5ybvjd6yjkoy3zvkghdx6ewcjokuoimded5yxk6hlq\":
      read tcp 10.0.12.89:58556->52.92.169.18:443:
        read: connection reset by peer
```